# Generated by Django 4.2 on 2023-05-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daberechi', '0004_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greetings_2',
            field=models.CharField(max_length=1000),
        ),
    ]
