# Generated by Django 4.2 on 2023-05-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daberechi', '0005_alter_home_greetings_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
