# Generated by Django 4.2 on 2023-05-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daberechi', '0006_skill_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='updated',
        ),
    ]
