# Generated by Django 4.2 on 2023-05-21 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daberechi', '0007_remove_skill_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
