# Generated by Django 4.2 on 2023-05-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daberechi', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
    ]
